Repository wecode-bootcamp-korea/45-1st-TRES-backend, pull requests merged in 2023-05, with the labels that each got.

#1 init
  tres-back/.env.sample
  tres-back/.gitignore
  tres-back/app.js
  tres-back/models/dataSource.js
  tres-back/package-lock.json
  tres-back/package.json
  tres-back/routes/index.js
Labels: 완료

#2 DB migration settings
  tres-back/controllers/orderController.js
  tres-back/controllers/productListController.js
  tres-back/controllers/userController.js
  tres-back/db/migrations/20230502101840_countries.sql
  tres-back/db/migrations/20230502101841_continents.sql
  tres-back/db/migrations/20230502101842_allergies.sql
  tres-back/db/migrations/20230502101843_meats.sql
  tres-back/db/migrations/20230502101844_images.sql
  tres-back/db/migrations/20230502101845_addresses.sql
  tres-back/db/migrations/20230502101846_users.sql
  tres-back/db/migrations/20230502101847_foods.sql
  tres-back/db/migrations/20230502101848_likes.sql
  tres-back/db/migrations/20230502101849_allergy_foods.sql
  tres-back/db/migrations/20230502101850_meat_foods.sql
  tres-back/db/migrations/20230502101851_order_status_code.sql
  tres-back/db/migrations/20230502101852_order_items.sql
  tres-back/db/migrations/20230502101853_orders.sql
  tres-back/db/migrations/20230502101854_user_addresses.sql
  tres-back/db/migrations/20230502101855_reviews.sql
Labels: 완료

#3 [45기 문승종] file root modified
  .env.sample
  .gitignore
  app.js
  controllers/orderController.js
  controllers/productListController.js
  controllers/userController.js
  db/migrations/20230502101840_countries.sql
  db/migrations/20230502101841_continents.sql
  db/migrations/20230502101842_allergies.sql
  db/migrations/20230502101843_meats.sql
  db/migrations/20230502101844_images.sql
  db/migrations/20230502101845_addresses.sql
  db/migrations/20230502101846_users.sql
  db/migrations/20230502101847_foods.sql
  db/migrations/20230502101848_likes.sql
  db/migrations/20230502101849_allergy_foods.sql
  db/migrations/20230502101850_meat_foods.sql
  db/migrations/20230502101851_order_status_code.sql
  db/migrations/20230502101852_order_items.sql
  db/migrations/20230502101853_orders.sql
  db/migrations/20230502101854_user_addresses.sql
  db/migrations/20230502101855_reviews.sql
  models/dataSource.js
  package-lock.json
  package.json
  routes/index.js
Labels: 멘토 리뷰 요청

#4 reoganization
  .gitignore
  controllers/productController.js
  db/migrations/20230502101845_addresses.sql
  db/migrations/20230502101846_users.sql
  models/orderDao.js
  models/productDao.js
  models/userDao.js
  routes/orderRouter.js
  routes/productRouter.js
  routes/userRouter.js
  services/orderService.js
  services/productService.js
  services/userService.js
Labels: 멘토 리뷰 요청

#5 Feature/db migration change
  db/migrations/20230502101840_countries.sql
  db/migrations/20230502101841_continents.sql
  db/migrations/20230502101854_user_addresses.sql
  db/migrations/20230503084222_country_user.sql
Labels: 멘토 리뷰 요청

#7 new DB
  db/migrations/20230502101846_users.sql
  db/migrations/20230502101847_foods.sql
  db/migrations/20230502101848_likes.sql
  db/migrations/20230502101849_allergy_foods.sql
  db/migrations/20230502101853_orders.sql
  db/migrations/20230502101855_reviews.sql
  db/migrations/20230504011305_continents.sql
  db/migrations/20230504011306_countries.sql
  db/migrations/20230504011309_allergies.sql
  db/migrations/20230504011312_meats.sql
  db/migrations/20230504011315_food_images.sql
  db/migrations/20230504011319_addresses.sql
  db/migrations/20230504011324_users.sql
  db/migrations/20230504011326_foods.sql
  db/migrations/20230504011334_likes.sql
  db/migrations/20230504011338_allergy_foods.sql
  db/migrations/20230504011342_meat_foods.sql
  db/migrations/20230504011345_order_status.sql
  db/migrations/20230504011349_order_items.sql
  db/migrations/20230504011352_orders.sql
  db/migrations/20230504011357_reviews.sql
  db/migrations/20230504011401_country_users.sql
Labels: 멘토 리뷰 요청

#10 [45기 하지현] Feature / Get foods list/ filtering, ordering, pagination
  .gitignore
  app.js
  controllers/productController.js
  models/productDao.js
  routes/index.js
  routes/productRouter.js
  services/productService.js
Labels: 멘토 리뷰 요청

#9 [45기문승종] signUp / login / getCountriesList / email, password validationCheck Token function
  app.js
  controllers/userController.js
  models/userDao.js
  routes/index.js
  routes/userRouter.js
  services/userService.js
  tres_final.sql
  utils/authorization.js
  utils/validationCheck.js
Labels: Conflict 해결 요청

#14 [45기 하지현] Error Handling
  app.js
  controllers/productController.js
  controllers/userController.js
  models/builder.js
  models/productDao.js
  models/userDao.js
  routes/index.js
  routes/productRouter.js
  services/productService.js
  services/userService.js
  tres_final.sql
  utils/authorization.js
  utils/error.js
  utils/validationCheck.js
Labels: 멘토 리뷰 요청

#11 [45기 장인석] ADD: main-page get data
  app.js
  controllers/productController.js
  models/productDao.js
  routes/index.js
  routes/productRouter.js
  services/productService.js
Labels: 멘토 리뷰 요청

#12 [45기 하지현] Feature / Get food information
  controllers/productController.js
  models/builder.js
  models/productDao.js
  routes/productRouter.js
  services/productService.js
Labels: 수정 요청

#18 [45기 하지현] FIX : filtering / get-food-info
  controllers/productController.js
  models/builder.js
  models/productDao.js
  services/productService.js
Labels: 멘토 리뷰 요청

#21 [45기 문승종] modified users_table, order_table
  db/migrations/20230509054053_modified_users.sql
  db/migrations/20230509054103_modified_orders.sql
Labels: 멘토 리뷰 요청

#22 [45기 문승종] modified userController
  controllers/userController.js
Labels: 멘토 리뷰 요청

#17 [45기 하지현] FEATURE : likes
  controllers/likesController.js
  controllers/productController.js
  models/likesDao.js
  routes/index.js
  routes/likesRouter.js
  services/likesService.js
  services/userService.js
Labels: 멘토 리뷰 요청

#19 Feature/delete product(s)/modify quantity
  .env.sample
  controllers/orderController.js
  controllers/userController.js
  db/migrations/20230506052824_modifications_two.sql
  models/orderDao.js
  routes/index.js
  routes/orderRouter.js
  routes/userRouter.js
  services/orderService.js
  services/userService.js
  utils/validationCheck.js
Labels: 완료

#23 [45기 하지현] FIX : 상품상세 query문 수정
  models/productDao.js
  services/productService.js
Labels: 멘토 리뷰 요청

#13 [45기 문승종] addCart, getCart, function apply transaction
  controllers/orderController.js
  models/orderDao.js
  routes/index.js
  routes/orderRouter.js
  routes/userRouter.js
  services/orderService.js
  utils/validationCheck.js
Labels: 멘토 리뷰 요청

#25 HOTFIX: Migration - order status relation
  db/migrations/20230510032341_order_tables_relation_change.sql
  models/orderDao.js
  services/orderService.js
Labels: 멘토 리뷰 요청, 완료

#26 Feature/main category
  controllers/productController.js
  models/productDao.js
  routes/productRouter.js
  services/productService.js
Labels: 멘토 리뷰 요청

#24 [45기 문승종] Apply transaction/signup function
  models/userDao.js
Labels: 멘토 리뷰 요청

#31 [45기 하지현] FIX : get-foods-list / get-random-products
  controllers/productController.js
  models/builder.js
  models/productDao.js
  services/productService.js
Labels: 멘토 리뷰 요청

#20 [45기 문승종] getUserCartInfo, payment function
  controllers/paymentController.js
  models/paymentDao.js
  routes/index.js
  routes/paymentRouter.js
  services/paymentService.js
  utils/validationCheck.js
Labels: 멘토 리뷰 요청

#32 MODIFY: prevent from having multiple rows of same item in cart
  models/orderDao.js
  routes/orderRouter.js
  services/orderService.js
Labels: 멘토 리뷰 요청

#34 Feature/check update address info
  controllers/paymentController.js
  models/paymentDao.js
  routes/paymentRouter.js
  services/paymentService.js
Labels: 멘토 리뷰 요청

#33 [45기 문승종] fix/paymentDao
  controllers/paymentController.js
  models/paymentDao.js
  models/userDao.js
  routes/paymentRouter.js
  services/paymentService.js
Labels: 완료

#37 [45기 하지현] refactoring
  controllers/orderController.js
  controllers/productController.js
  controllers/userController.js
  models/orderDao.js
  models/paymentDao.js
  models/productDao.js
  models/userDao.js
  routes/likesRouter.js
  routes/productRouter.js
  services/orderService.js
  services/paymentService.js
  utils/authorization.js
  utils/validationCheck.js
Labels: Conflict 해결 요청

#42 Fix/refactoring
  controllers/likesController.js
  controllers/orderController.js
  controllers/paymentController.js
  controllers/productController.js
  models/likesDao.js
  models/orderDao.js
  models/paymentDao.js
  models/productDao.js
  models/userDao.js
  routes/orderRouter.js
  routes/userRouter.js
  services/likesService.js
  services/orderService.js
  services/paymentService.js
  utils/authorization.js
  utils/validationCheck.js
Labels: 멘토 리뷰 요청

#44 [45기 하지현] fix : productDao
  models/productDao.js
Labels: 멘토 리뷰 요청
